name: Deploy to VPS Instance

on:
    pull_request:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up SSH agent
              uses: webfactory/ssh-agent@v0.5.3
              with:
                  ssh-private-key: ${{ secrets.SSH_KEY }}

            - name: Deploy to VPS Instance
              run: |
                  ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "cd ~/sgheda/prod/sgheda-frontend-new && git pull origin main && yarn build && pm2 reload 'sgheda-server'"
